spring.application.name=ScanToOrder
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.main.allow-circular-references=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.repositories.enabled=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.generate-ddl=true
paystack.secret.key=${PAYSTACK_SECRET_KEY}
paystack.base.url=${PAYSTACK_BASE_URL}
paystack.callback.url=${PAYSTACK_CALLBACK_URL}
app.frontend.url=${FRONTEND_URL}
